// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xquiezxkxvrngmehqnmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxdWllenhreHZybmdtZWhxbm1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODg5NDMsImV4cCI6MjA2NTI2NDk0M30.tPKFs5ZQItnVEXGgN47stz3UhSEXSM-kJTUXTloq6wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);